# Generated by Django 4.2 on 2023-04-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0003_category_drugs_order_orderofprovider_delete_chart_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
